# Generated by Django 5.1.2 on 2024-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstypes',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
