# Generated by Django 5.1.2 on 2024-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szmm', '0003_goodstype_pulsator_delete_goodstypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulsator',
            old_name='image_link',
            new_name='image_link_1',
        ),
        migrations.AddField(
            model_name='pulsator',
            name='image_link_2',
            field=models.ImageField(blank=True, null=True, upload_to='pulsator_images/'),
        ),
        migrations.AddField(
            model_name='pulsator',
            name='image_link_3',
            field=models.ImageField(blank=True, null=True, upload_to='pulsator_images/'),
        ),
        migrations.AddField(
            model_name='pulsator',
            name='image_link_4',
            field=models.ImageField(blank=True, null=True, upload_to='pulsator_images/'),
        ),
        migrations.AddField(
            model_name='pulsator',
            name='image_link_5',
            field=models.ImageField(blank=True, null=True, upload_to='pulsator_images/'),
        ),
    ]
