# Generated by Django 5.1.2 on 2024-11-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szmm', '0005_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='image_link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='pulsator',
            old_name='image_link_1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='pulsator',
            old_name='image_link_2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='pulsator',
            old_name='image_link_3',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='pulsator',
            old_name='image_link_4',
            new_name='image_4',
        ),
        migrations.RenameField(
            model_name='pulsator',
            old_name='image_link_5',
            new_name='image_5',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='image_link',
            new_name='image',
        ),
    ]
